### ISSUE TITLE
AppendSpan

### ISSUE THREAD

**Issue by bCamba** [linkdotnet/StringBuilder#208]
Can we have a method like AppendSpan of the [internal .NET ValueStringBuilder](https://github.com/dotnet/runtime/blob/e65457031da52f57d03da721f381a82a5be64c03/src/libraries/Common/src/System/Text/ValueStringBuilder.cs#L266C9-L277C10)?

**Comment by linkdotnet** [comment]
Sure and thanks for taking the lead!

**Comment by linkdotnet** [comment]
Thanks again for the work! Will close the issue and create the 1.22 release
